CREATE TABLE USERS(
    ID                  BIGINT          PRIMARY KEY AUTO_INCREMENT,
    USERNAME            VARCHAR(64)     NOT NULL UNIQUE,
    EMAIL               VARCHAR(64)     NOT NULL UNIQUE,
    FIRST_NAME          VARCHAR(128),
    LAST_NAME           VARCHAR(128),
    STATUS              VARCHAR(64)     DEFAULT 'ACTIVE',
    CREATE_TIME         TIMESTAMP(6)    NOT NULL,
    CREATE_BY           TIMESTAMP(6)    NOT NULL,
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    INTERNAL_VERSION    BIGINT          DEFAULT 1
);

CREATE TABLE ACTIVITY_USERS(
    ACTIVITY_ID         BIGINT          PRIMARY KEY AUTO_INCREMENT,
    USER_ID             BIGINT,
    USERNAME            VARCHAR(64),
    EMAIL               VARCHAR(64),
    FIRST_NAME          VARCHAR(128),
    LAST_NAME           VARCHAR(128),
    STATUS              VARCHAR(64),
    CREATE_TIME         TIMESTAMP(6),
    CREATE_BY           TIMESTAMP(6),
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    ACTIVITY_USER       VARCHAR(64)     NOT NULL,
    ACTIVITY_ACTION     INT             NOT NULL,
    ACTIVITY_TIME       TIMESTAMP(6)    NOT NULL,
    INTERNAL_VERSION    BIGINT          DEFAULT 1
);

CREATE TABLE PROJECTS(
    ID                  BIGINT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME                VARCHAR(64)     NOT NULL,
    DESCRIPTION         VARCHAR(128),
    STATUS              VARCHAR(64)     DEFAULT 'ACTIVE',
    CREATE_TIME         TIMESTAMP(6)    NOT NULL,
    CREATE_BY           TIMESTAMP(6)    NOT NULL,
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    INTERNAL_VERSION    BIGINT          DEFAULT 1
);

CREATE TABLE ACTIVITY_PROJECTS(
    ACTIVITY_ID         BIGINT          PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ID          BIGINT,
    NAME                VARCHAR(64),
    DESCRIPTION         VARCHAR(128),
    STATUS              VARCHAR(64),
    CREATE_TIME         TIMESTAMP(6),
    CREATE_BY           TIMESTAMP(6),
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    ACTIVITY_USER       VARCHAR(64)     NOT NULL,
    ACTIVITY_ACTION     INT             NOT NULL,
    ACTIVITY_TIME       TIMESTAMP(6)    NOT NULL,
    INTERNAL_VERSION    BIGINT          DEFAULT 1
);

CREATE TABLE TASKS(
    ID                  BIGINT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION         VARCHAR(512)    NOT NULL,
    STATUS              VARCHAR(64)     DEFAULT 'OPEN',
    PROJECT             BIGINT          NOT NULL,
    DEU_DATE            DATE,
    CREATE_TIME         TIMESTAMP(6)    NOT NULL,
    CREATE_BY           TIMESTAMP(6)    NOT NULL,
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    INTERNAL_VERSION    BIGINT          DEFAULT 1,
    FOREIGN KEY (PROJECT) REFERENCES PROJECTS(ID) ON DELETE CASCADE
);

CREATE TABLE ACTIVITY_TASKS(
    ACTIVITY_ID         BIGINT          PRIMARY KEY AUTO_INCREMENT,
    TASK_ID             BIGINT,
    DESCRIPTION         VARCHAR(512),
    STATUS              VARCHAR(64),
    PROJECT             VARCHAR(64),
    DEU_DATE            DATE,
    CREATE_TIME         TIMESTAMP(6),
    CREATE_BY           TIMESTAMP(6),
    EDIT_TIME           TIMESTAMP(6),
    EDITED_BY           TIMESTAMP(6),
    ACTIVITY_USER       VARCHAR(64)     NOT NULL,
    ACTIVITY_ACTION     INT             NOT NULL,
    ACTIVITY_TIME       TIMESTAMP(6)    NOT NULL,
    INTERNAL_VERSION    BIGINT          DEFAULT 1
);