INSERT INTO ROLE(ID, NAME, CREATE_TIME, CREATED_BY) VALUES (1, 'ADMIN', NOW(), 'System');

INSERT INTO ROLE(ID, NAME, CREATE_TIME, CREATED_BY) VALUES (2, 'USER', NOW(), 'System');

INSERT INTO USER(USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, STATUS, CREATE_TIME, CREATED_BY)
VALUES ('admin', '$2a$10$kBhAt4LDE9Zg/P.LhXi8/.k837/mGNUVgBeT/9QZ/ovggCgNWJdkW', 'hello.admin@taskmanager.com',
        'Super', 'Admin', 'ACTIVE', NOW(), 'System');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID, ROLE_NAME, CREATE_TIME, CREATED_BY)
VALUES (LAST_INSERT_ID(), 1, 'ADMIN', NOW(), 'System');

INSERT INTO USER(USERNAME, PASSWORD, EMAIL, FIRST_NAME, LAST_NAME, STATUS, CREATE_TIME, CREATED_BY)
VALUES ('user', '$2a$10$GmBKl1qjd8iCUJQPxKRj0OPIsf5xvN0ssRr8PkBBU2JKDRaL8Z4jm', 'hello.user@taskmanager.com',
        'Default', 'User', 'ACTIVE', NOW(), 'System');

INSERT INTO USER_ROLES(USER_ID, ROLE_ID, ROLE_NAME, CREATE_TIME, CREATED_BY)
VALUES (LAST_INSERT_ID(), 2, 'USER', NOW(), 'System');