INSERT INTO ROLE(ID, NAME, CREATE_TIME, CREATE_BY, EDIT_TIME, EDITED_BY, INTERNAL_VERSION)
VALUES (1, 'ADMIN', now(), 'System', null, null, 1);
INSERT INTO ROLE(ID, NAME, CREATE_TIME, CREATE_BY, EDIT_TIME, EDITED_BY, INTERNAL_VERSION)
VALUES (2, 'USER', now(), 'System', null, null, 1);